# Generated by Django 4.2 on 2023-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qna_title', models.CharField(max_length=30)),
                ('qna_content', models.TextField(max_length=500)),
                ('qna_created_at', models.DateTimeField(auto_now_add=True)),
                ('qna_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Qna_register',
            },
        ),
    ]
