# Generated by Django 4.2 on 2023-04-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_rename_content_qnamodel_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnamodel',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
