# Generated by Django 4.2 on 2023-04-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_rename_create_at_qnamodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnamodel',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
