# Generated by Django 4.2 on 2023-04-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_rename_create_at_qnamodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qnamodel',
            name='author',
        ),
    ]
