# Generated by Django 4.2 on 2023-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
