# Generated by Django 4.2 on 2023-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testkey', models.ManyToManyField(blank=True, to='testapp.testapp')),
            ],
            options={
                'db_table': 'my_page',
            },
        ),
    ]
