# Generated by Django 4.2 on 2023-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_key', models.ManyToManyField(blank=True, related_name='mypage_key', to='challenge.challengemodel')),
            ],
            options={
                'db_table': 'my_page',
            },
        ),
    ]
