# Generated by Django 4.2 on 2023-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qna_key', models.ManyToManyField(blank=True, related_name='mypage_key', to='qna.qnamodel')),
            ],
            options={
                'db_table': 'my_page',
            },
        ),
    ]
