# Generated by Django 4.2 on 2023-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qna', '0001_initial'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='qna_key',
            field=models.ManyToManyField(blank=True, related_name='mypage_key', to='qna.qnamodel'),
        ),
    ]
