# Generated by Django 4.2 on 2023-04-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='follow',
            field=models.ManyToManyField(related_name='Products', to='testapp.products'),
        ),
    ]
