# Generated by Django 4.2 on 2023-04-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_alter_mypage_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypage',
            old_name='follow',
            new_name='userkey',
        ),
        migrations.AlterModelTable(
            name='mypage',
            table='my_page',
        ),
    ]
